# site settings
title: Shaun
subtitle: by Shaun Keenan
email: skeenan@gmail.com
description: My Blog
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://skeenan947.github.io" # the base hostname & protocol for your site
author: Shaun Keenan
street_address: 1234 Somewhere Road
city: Nope
state: NA
zip_code: 55555
country: United States of America
phone: Nope

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/skeenan947
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/skeenan2501

# build settings
markdown: kramdown

sass:
  style: compressed
